language: cpp

os: linux
sudo: required
dist: trusty

compiler:
  - gcc
  - clang
before_script:
  - BUILD_DIR=`pwd`/builds
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
script:
  - cd ${BUILD_DIR}
  - make
